### ISSUE TITLE
Allow users to pass in a timeout for the API client

### ISSUE THREAD

**Issue by gabbifish** [cloudflare/cloudflare-rs#45]
This is related to https://github.com/cloudflare/wrangler/issues/746.

Ideally, users should be allowed to specify the API client timeout period when constructing the API client with `HttpApiClient::new()`. What do you think?

**Comment by adamchalmers** [comment]
I agree!

**Comment by gabbifish** [comment]
Thinking about the maintainability of this in the long term... perhaps we want to make the `HttpApiClient` 's `http_client` field mutable, so a user of cloudflare-rs can customize this client field themselves however they see fit using https://docs.rs/reqwest/0.8.4/reqwest/struct.ClientBuilder.html. If we move a `timeout` param into the `Http::ApiClient::new()` function, I do wonder if that will be the beginning of bloating `new()` with new param arguments.

I think I prefer having the `http_api` field in `HttpApiClient` become `mut` so users can provide their own `reqwest::Client` with all their custom configs there. What do you think?

**Comment by gabbifish** [comment]
or, we can even implement `HttpApiClient::from(reqwest_client)`?

**Comment by ashleymichal** [comment]
i personally prefer a constructor argument to a mutable struct field.

**Comment by adamchalmers** [comment]
100% agree with Ashley

**Comment by gabbifish** [comment]
Alright, I'll get going with this then! :)
