### ISSUE TITLE
Zone listing endpoint not working

### ISSUE THREAD

**Issue by tungd** [cloudflare/cloudflare-rs#75]
Hi, I tried to call `ListZones` and it doesn't work. The error is:

```
invalid value: integer `-64315`, expected u8 at line 1 column 142
```

I checked the response and it's `development_mode` field.

**Comment by rakshith-ravi** [comment]
Wait how do you call `ListZones`? I tried calling it but it requires an identifier which I'm not sure what to put the value as. Additionally, there's no way for me to pass the parameters that I need to. Any help would be appreciated.

**Comment by tungd** [comment]
> Wait how do you call `ListZones`? I tried calling it but it requires an identifier which I'm not sure what to put the value as. Additionally, there's no way for me to pass the parameters that I need to. Any help would be appreciated.

At the time I wrote this, the zone listing API didn't support any parameters at all. You can use any `str` for identifier it wasn't used in any way. 

There is an open PR updating this endpoint, you can use their fork at the moment. Otherwise, I don't think there will be too many zones per account, so you could just use this method and do any filtering necessary by yourselves.

**Comment by rakshith-ravi** [comment]
Not sure if I'm doing something wrong, but when I call the `ListZones` request (as `client.request(&zone::ListZones {identifier: ""}).unwrap();`, I get the following error:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Invalid(reqwest::Error { kind: Decode, source: Error("missing field `settings`", line: 1, column: 900) })', api/src/scheduler/domain.rs:160:10
```

Am I doing something wrong?
