### ISSUE TITLE
JSON deserialization doesn't work for zones with free plans

### ISSUE THREAD

**Issue by nickvollmar** [cloudflare/cloudflare-rs#8]
A free zone has the following `plan` object:
```
{
    "id": "0feeeeeeeeeeeeeeeeeeeeeeeeeeeeee",
    "name": "Free Website",
    "price": 0,
    "currency": "USD",
    "frequency": "",
    "is_subscribed": true,
    "can_subscribe": false,
    "legacy_id": "free",
    "legacy_discount": false,
    "externally_managed": false
}
```

Notably, `frequency: ""`. This causes Rust deserialization to fail:
```
unknown variant ``, expected one of `weekly`, `monthly`, `quarterly`, `yearly`
```

---

I think this is _technically_ in the Cloudflare API docs. The section https://api.cloudflare.com/#zone-properties has this to say about frequency:
```
valid values: weekly, monthly, quarterly, yearly,
```
Note the trailing comma. I think the API documentation-generator is faithfully stripping the quotes from every possible value, including the empty string...

**Comment by adamchalmers** [comment]
Sigh. We should fix the documentation as well.
